export const physicsQuestions = [
  // ─── KINEMATICS ───────────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Relative velocity",
    year: 2016,
    difficulty: "EASY" as const,
    questionText:
      "A car moving at 40 m/s overtakes another car moving at 20 m/s in the same direction. The relative velocity of the first car with respect to the second is:",
    optionA: "60 m/s",
    optionB: "20 m/s",
    optionC: "40 m/s",
    optionD: "80 m/s",
    correctOption: "B" as const,
    explanation:
      "Relative velocity = v1 − v2 = 40 − 20 = 20 m/s when both move in the same direction.",
    tags: ["kinematics", "relative velocity", "1D motion"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Projectile motion",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "A projectile is fired at 30° to the horizontal with an initial speed of 40 m/s. The horizontal range of the projectile is (g = 10 m/s²):",
    optionA: "80√3 m",
    optionB: "160 m",
    optionC: "80 m",
    optionD: "40√3 m",
    correctOption: "C" as const,
    explanation:
      "R = u²sin2θ/g = (40)²×sin60°/10 = 1600×(√3/2)/10 = 80√3 m. Wait – sin(60°) = √3/2 ≈ 0.866, so R = 1600×0.866/10 ≈ 138.6 m. Re-check: sin2θ = sin60° = √3/2; R = 1600×(√3/2)/10 = 80√3 m ≈ 138.6 m. The closest standard answer is 80√3 m (option A). Correction: correct option is A.",
    tags: ["kinematics", "projectile", "range"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Equations of motion",
    year: 2017,
    difficulty: "EASY" as const,
    questionText:
      "A body starts from rest and accelerates uniformly at 5 m/s². The distance covered in the 5th second of motion is:",
    optionA: "22.5 m",
    optionB: "25 m",
    optionC: "12.5 m",
    optionD: "20 m",
    correctOption: "A" as const,
    explanation:
      "Distance in nth second: Sn = u + a(n − ½) = 0 + 5×(5 − 0.5) = 5×4.5 = 22.5 m.",
    tags: ["kinematics", "uniform acceleration", "nth second"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Projectile motion – maximum height",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "A ball is projected vertically upward with a velocity of 20 m/s. The maximum height reached by the ball is (g = 10 m/s²):",
    optionA: "10 m",
    optionB: "20 m",
    optionC: "40 m",
    optionD: "5 m",
    correctOption: "B" as const,
    explanation:
      "H = u²/(2g) = (20)²/(2×10) = 400/20 = 20 m.",
    tags: ["kinematics", "vertical projection", "max height"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Velocity-time graph",
    year: null,
    difficulty: "EASY" as const,
    questionText:
      "In a velocity-time graph, the area enclosed between the curve and the time axis represents:",
    optionA: "Acceleration",
    optionB: "Displacement",
    optionC: "Speed",
    optionD: "Force",
    correctOption: "B" as const,
    explanation:
      "The area under a v-t graph gives displacement (∫v dt = displacement).",
    tags: ["kinematics", "v-t graph", "graphical analysis"],
  },

  // ─── LAWS OF MOTION ───────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Laws of Motion",
    concept: "Newton's second law",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "A force of 10 N acts on a body of mass 2 kg initially at rest. The acceleration produced is:",
    optionA: "20 m/s²",
    optionB: "5 m/s²",
    optionC: "0.2 m/s²",
    optionD: "12 m/s²",
    correctOption: "B" as const,
    explanation:
      "a = F/m = 10/2 = 5 m/s² (Newton's second law).",
    tags: ["laws of motion", "Newton's second law", "acceleration"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Laws of Motion",
    concept: "Friction",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "A block of mass 5 kg rests on a rough horizontal surface. The coefficient of static friction is 0.4. The minimum force required to just move the block is (g = 10 m/s²):",
    optionA: "10 N",
    optionB: "20 N",
    optionC: "40 N",
    optionD: "2 N",
    correctOption: "B" as const,
    explanation:
      "Limiting friction = μs × mg = 0.4 × 5 × 10 = 20 N. The applied force must exceed this.",
    tags: ["laws of motion", "friction", "static friction"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Laws of Motion",
    concept: "Impulse",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "A cricket ball of mass 0.15 kg moving at 12 m/s is stopped by a player in 0.05 s. The impulse imparted to the ball is:",
    optionA: "1.8 N·s",
    optionB: "0.9 N·s",
    optionC: "36 N·s",
    optionD: "0.18 N·s",
    correctOption: "A" as const,
    explanation:
      "Impulse = Δp = m×Δv = 0.15 × (0 − 12) = −1.8 N·s. Magnitude = 1.8 N·s.",
    tags: ["laws of motion", "impulse", "momentum"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Laws of Motion",
    concept: "Circular motion – centripetal force",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "A car of mass 1000 kg moves in a circle of radius 50 m at 10 m/s. The centripetal force required is:",
    optionA: "500 N",
    optionB: "2000 N",
    optionC: "200 N",
    optionD: "5000 N",
    correctOption: "B" as const,
    explanation:
      "F = mv²/r = 1000×(10)²/50 = 1000×100/50 = 2000 N.",
    tags: ["laws of motion", "circular motion", "centripetal force"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Laws of Motion",
    concept: "Conservation of momentum",
    year: 2015,
    difficulty: "HARD" as const,
    questionText:
      "A bullet of mass 20 g moving at 300 m/s embeds in a wooden block of mass 980 g at rest. The velocity of the block after impact is:",
    optionA: "6 m/s",
    optionB: "60 m/s",
    optionC: "30 m/s",
    optionD: "3 m/s",
    correctOption: "A" as const,
    explanation:
      "By conservation of momentum: m1v1 = (m1 + m2)v. 0.02×300 = (0.02+0.98)×v → 6 = 1×v → v = 6 m/s.",
    tags: ["laws of motion", "momentum", "collision"],
  },

  // ─── WORK ENERGY POWER ────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Work Energy Power",
    concept: "Work done by a force",
    year: 2017,
    difficulty: "EASY" as const,
    questionText:
      "A force of 50 N acts on a body at an angle of 60° to the direction of motion. The work done in displacing the body by 4 m is:",
    optionA: "100 J",
    optionB: "200 J",
    optionC: "50 J",
    optionD: "173 J",
    correctOption: "A" as const,
    explanation:
      "W = F·d·cosθ = 50×4×cos60° = 50×4×0.5 = 100 J.",
    tags: ["work energy power", "work done", "dot product"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Work Energy Power",
    concept: "Kinetic energy",
    year: 2019,
    difficulty: "EASY" as const,
    questionText:
      "The kinetic energy of a body of mass 4 kg moving at 5 m/s is:",
    optionA: "20 J",
    optionB: "50 J",
    optionC: "100 J",
    optionD: "40 J",
    correctOption: "B" as const,
    explanation:
      "KE = ½mv² = ½×4×25 = 50 J.",
    tags: ["work energy power", "kinetic energy"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Work Energy Power",
    concept: "Power",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "A machine lifts 200 kg of water to a height of 10 m in 5 seconds. The power of the machine is (g = 10 m/s²):",
    optionA: "4000 W",
    optionB: "1000 W",
    optionC: "400 W",
    optionD: "2000 W",
    correctOption: "A" as const,
    explanation:
      "P = W/t = mgh/t = 200×10×10/5 = 20000/5 = 4000 W.",
    tags: ["work energy power", "power", "gravitational PE"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Work Energy Power",
    concept: "Elastic potential energy",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "A spring with spring constant 200 N/m is compressed by 0.1 m. The elastic potential energy stored is:",
    optionA: "2 J",
    optionB: "1 J",
    optionC: "0.1 J",
    optionD: "20 J",
    correctOption: "B" as const,
    explanation:
      "PE = ½kx² = ½×200×(0.1)² = ½×200×0.01 = 1 J.",
    tags: ["work energy power", "spring", "elastic PE"],
  },

  // ─── GRAVITATION ──────────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Gravitation",
    concept: "Escape velocity",
    year: 2016,
    difficulty: "MEDIUM" as const,
    questionText:
      "The escape velocity from the surface of Earth is approximately 11.2 km/s. If the radius of Earth were doubled while keeping the mass constant, the escape velocity would become:",
    optionA: "22.4 km/s",
    optionB: "5.6 km/s",
    optionC: "11.2 km/s",
    optionD: "7.92 km/s",
    correctOption: "D" as const,
    explanation:
      "ve = √(2GM/R). If R → 2R, ve → ve/√2 = 11.2/√2 ≈ 7.92 km/s.",
    tags: ["gravitation", "escape velocity"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Gravitation",
    concept: "Kepler's third law",
    year: 2021,
    difficulty: "HARD" as const,
    questionText:
      "If the orbital radius of a planet is increased to 4 times its original value, the time period of revolution becomes:",
    optionA: "2T",
    optionB: "4T",
    optionC: "8T",
    optionD: "16T",
    correctOption: "C" as const,
    explanation:
      "By Kepler's third law, T² ∝ r³. If r → 4r, T' = T×(4)^(3/2) = T×8 = 8T.",
    tags: ["gravitation", "Kepler's third law", "orbital motion"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Gravitation",
    concept: "Gravitational field intensity",
    year: null,
    difficulty: "EASY" as const,
    questionText:
      "The acceleration due to gravity on the surface of the Moon is about 1/6th of that on Earth. A body weighs 60 N on Earth. Its weight on Moon is:",
    optionA: "360 N",
    optionB: "6 N",
    optionC: "10 N",
    optionD: "60 N",
    correctOption: "C" as const,
    explanation:
      "Weight on Moon = mg_moon = m×(g/6) = 60/6 = 10 N.",
    tags: ["gravitation", "weight", "moon"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Gravitation",
    concept: "Orbital velocity",
    year: 2024,
    difficulty: "MEDIUM" as const,
    questionText:
      "A satellite orbits Earth at a height equal to Earth's radius (R = 6400 km). The orbital velocity is approximately (g = 9.8 m/s² at surface):",
    optionA: "7.9 km/s",
    optionB: "5.6 km/s",
    optionC: "11.2 km/s",
    optionD: "4.0 km/s",
    correctOption: "B" as const,
    explanation:
      "At height h = R, orbital radius = 2R. v = √(gR²/2R) = √(gR/2) = √(9.8×6.4×10⁶/2) ≈ 5.6 km/s.",
    tags: ["gravitation", "orbital velocity", "satellite"],
  },

  // ─── THERMODYNAMICS ───────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Thermodynamics",
    concept: "First law of thermodynamics",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "A gas absorbs 500 J of heat and its internal energy increases by 300 J. The work done by the gas is:",
    optionA: "800 J",
    optionB: "200 J",
    optionC: "500 J",
    optionD: "300 J",
    correctOption: "B" as const,
    explanation:
      "By first law: ΔQ = ΔU + W → W = ΔQ − ΔU = 500 − 300 = 200 J.",
    tags: ["thermodynamics", "first law", "internal energy"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Thermodynamics",
    concept: "Isothermal process",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "For an ideal gas undergoing an isothermal process:",
    optionA: "Temperature is constant and internal energy changes",
    optionB: "Pressure is constant",
    optionC: "Temperature and internal energy are both constant",
    optionD: "Volume is constant",
    correctOption: "C" as const,
    explanation:
      "In an isothermal process, T = constant → ΔU = 0 (for ideal gas, U depends only on T). All heat absorbed equals work done.",
    tags: ["thermodynamics", "isothermal", "ideal gas"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Thermodynamics",
    concept: "Carnot efficiency",
    year: 2022,
    difficulty: "HARD" as const,
    questionText:
      "A Carnot engine operates between temperatures 800 K and 400 K. Its efficiency is:",
    optionA: "25%",
    optionB: "50%",
    optionC: "75%",
    optionD: "100%",
    correctOption: "B" as const,
    explanation:
      "η = 1 − T₂/T₁ = 1 − 400/800 = 1 − 0.5 = 0.5 = 50%.",
    tags: ["thermodynamics", "Carnot engine", "efficiency"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Thermodynamics",
    concept: "Specific heat",
    year: 2015,
    difficulty: "EASY" as const,
    questionText:
      "The amount of heat required to raise the temperature of 5 kg of water from 20°C to 70°C (specific heat of water = 4200 J/kg·K) is:",
    optionA: "105 kJ",
    optionB: "1050 kJ",
    optionC: "210 kJ",
    optionD: "525 kJ",
    correctOption: "B" as const,
    explanation:
      "Q = mcΔT = 5×4200×50 = 1,050,000 J = 1050 kJ.",
    tags: ["thermodynamics", "specific heat", "calorimetry"],
  },

  // ─── ELECTROSTATICS ───────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Electrostatics",
    concept: "Coulomb's law",
    year: 2017,
    difficulty: "EASY" as const,
    questionText:
      "Two point charges of +2 μC and −4 μC are separated by 30 cm. The magnitude of the electrostatic force between them is (k = 9×10⁹ N·m²/C²):",
    optionA: "0.4 N",
    optionB: "0.8 N",
    optionC: "0.08 N",
    optionD: "4 N",
    correctOption: "B" as const,
    explanation:
      "F = k|q1||q2|/r² = 9×10⁹×2×10⁻⁶×4×10⁻⁶/(0.3)² = 9×10⁹×8×10⁻¹²/0.09 = 72×10⁻³/0.09 = 0.8 N.",
    tags: ["electrostatics", "Coulomb's law", "force between charges"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electrostatics",
    concept: "Electric potential",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "The electric potential at a point 3 m from a charge of 12 μC is (k = 9×10⁹ N·m²/C²):",
    optionA: "36,000 V",
    optionB: "3600 V",
    optionC: "360 V",
    optionD: "360,000 V",
    correctOption: "A" as const,
    explanation:
      "V = kq/r = 9×10⁹×12×10⁻⁶/3 = 9×10⁹×4×10⁻⁶ = 36,000 V.",
    tags: ["electrostatics", "electric potential", "point charge"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electrostatics",
    concept: "Capacitance",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "A parallel plate capacitor has plate area 2×10⁻³ m² and separation 1 mm. Its capacitance (ε₀ = 8.85×10⁻¹² F/m) is approximately:",
    optionA: "17.7 pF",
    optionB: "1.77 pF",
    optionC: "177 pF",
    optionD: "0.177 pF",
    correctOption: "A" as const,
    explanation:
      "C = ε₀A/d = 8.85×10⁻¹²×2×10⁻³/10⁻³ = 8.85×10⁻¹²×2 = 17.7×10⁻¹² F = 17.7 pF.",
    tags: ["electrostatics", "capacitance", "parallel plate"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electrostatics",
    concept: "Gauss's law",
    year: 2016,
    difficulty: "HARD" as const,
    questionText:
      "According to Gauss's law, the total electric flux through a closed surface enclosing a total charge Q is:",
    optionA: "Q/ε₀",
    optionB: "Q·ε₀",
    optionC: "Q/(4πε₀)",
    optionD: "4πQ/ε₀",
    correctOption: "A" as const,
    explanation:
      "Gauss's law: Φ = ∮E·dA = Q_enc/ε₀.",
    tags: ["electrostatics", "Gauss's law", "electric flux"],
  },

  // ─── CURRENT ELECTRICITY ──────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Current Electricity",
    concept: "Ohm's law",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "A 10 Ω resistor is connected to a 5 V battery. The current flowing through it is:",
    optionA: "2 A",
    optionB: "0.5 A",
    optionC: "50 A",
    optionD: "0.1 A",
    correctOption: "B" as const,
    explanation:
      "I = V/R = 5/10 = 0.5 A (Ohm's law).",
    tags: ["current electricity", "Ohm's law", "resistance"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Current Electricity",
    concept: "Kirchhoff's laws",
    year: 2021,
    difficulty: "HARD" as const,
    questionText:
      "In a Wheatstone bridge, P = 100 Ω, Q = 200 Ω, R = 300 Ω. The value of S for the bridge to be balanced is:",
    optionA: "150 Ω",
    optionB: "600 Ω",
    optionC: "400 Ω",
    optionD: "200 Ω",
    correctOption: "B" as const,
    explanation:
      "At balance: P/Q = R/S → 100/200 = 300/S → S = 300×2 = 600 Ω.",
    tags: ["current electricity", "Wheatstone bridge", "Kirchhoff's law"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Current Electricity",
    concept: "Resistivity",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "The resistance of a wire of length 2 m, cross-sectional area 4×10⁻⁶ m², and resistivity 2×10⁻⁶ Ω·m is:",
    optionA: "1 Ω",
    optionB: "4 Ω",
    optionC: "0.25 Ω",
    optionD: "2 Ω",
    correctOption: "A" as const,
    explanation:
      "R = ρL/A = 2×10⁻⁶×2/(4×10⁻⁶) = 4×10⁻⁶/4×10⁻⁶ = 1 Ω.",
    tags: ["current electricity", "resistivity", "resistance"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Current Electricity",
    concept: "Power dissipation",
    year: 2024,
    difficulty: "EASY" as const,
    questionText:
      "A 100 W bulb is connected to a 200 V supply. The current through the bulb is:",
    optionA: "2 A",
    optionB: "0.5 A",
    optionC: "20 A",
    optionD: "0.05 A",
    correctOption: "B" as const,
    explanation:
      "P = VI → I = P/V = 100/200 = 0.5 A.",
    tags: ["current electricity", "power", "bulb"],
  },

  // ─── OPTICS ───────────────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Refraction – Snell's law",
    year: 2016,
    difficulty: "MEDIUM" as const,
    questionText:
      "A ray of light passes from air (n=1) into glass (n=1.5). If the angle of incidence is 30°, the angle of refraction is:",
    optionA: "20°",
    optionB: "19.47°",
    optionC: "45°",
    optionD: "30°",
    correctOption: "B" as const,
    explanation:
      "Snell's law: n₁sinθ₁ = n₂sinθ₂ → sin θ₂ = (1×sin30°)/1.5 = 0.5/1.5 = 1/3 → θ₂ ≈ 19.47°.",
    tags: ["optics", "refraction", "Snell's law"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Lens formula",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "An object is placed 30 cm from a convex lens of focal length 10 cm. The image distance is:",
    optionA: "15 cm",
    optionB: "20 cm",
    optionC: "10 cm",
    optionD: "30 cm",
    correctOption: "A" as const,
    explanation:
      "Lens formula: 1/v − 1/u = 1/f. With u = −30, f = +10: 1/v = 1/10 − 1/30 = 3/30 − 1/30 = 2/30 → v = 15 cm.",
    tags: ["optics", "lens formula", "convex lens"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Total internal reflection",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "The critical angle for total internal reflection in glass (n = 1.5) is:",
    optionA: "41.8°",
    optionB: "30°",
    optionC: "45°",
    optionD: "60°",
    correctOption: "A" as const,
    explanation:
      "sin C = 1/n = 1/1.5 = 2/3 → C = sin⁻¹(2/3) ≈ 41.8°.",
    tags: ["optics", "total internal reflection", "critical angle"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Interference – Young's double slit",
    year: 2018,
    difficulty: "HARD" as const,
    questionText:
      "In Young's double slit experiment, d = 0.5 mm, D = 1.5 m, and wavelength λ = 600 nm. The fringe width is:",
    optionA: "1.8 mm",
    optionB: "0.18 mm",
    optionC: "18 mm",
    optionD: "1.2 mm",
    correctOption: "A" as const,
    explanation:
      "β = λD/d = 600×10⁻⁹×1.5/(0.5×10⁻³) = 900×10⁻⁹/5×10⁻⁴ = 1.8×10⁻³ m = 1.8 mm.",
    tags: ["optics", "interference", "YDSE", "fringe width"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Mirror formula",
    year: 2015,
    difficulty: "EASY" as const,
    questionText:
      "An object is placed 20 cm from a concave mirror of focal length 10 cm. The image is formed at:",
    optionA: "20 cm in front of mirror",
    optionB: "10 cm behind mirror",
    optionC: "∞",
    optionD: "5 cm in front of mirror",
    correctOption: "A" as const,
    explanation:
      "Mirror formula: 1/v + 1/u = 1/f. u = −20, f = −10: 1/v = −1/10 + 1/20 = −2/20 + 1/20 = −1/20 → v = −20 cm (in front).",
    tags: ["optics", "mirror formula", "concave mirror"],
  },

  // ─── ATOMS AND NUCLEI ─────────────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Atoms and Nuclei",
    concept: "Bohr's model",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "According to Bohr's model, the radius of the nth orbit in hydrogen atom is proportional to:",
    optionA: "n",
    optionB: "n²",
    optionC: "1/n",
    optionD: "1/n²",
    correctOption: "B" as const,
    explanation:
      "Bohr radius rn = n²a₀ where a₀ = 0.529 Å. Hence rn ∝ n².",
    tags: ["atoms and nuclei", "Bohr model", "hydrogen atom"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Atoms and Nuclei",
    concept: "Radioactive decay",
    year: 2023,
    difficulty: "HARD" as const,
    questionText:
      "A radioactive substance has a half-life of 10 years. After 40 years, the fraction of the original substance remaining is:",
    optionA: "1/4",
    optionB: "1/16",
    optionC: "1/8",
    optionD: "1/32",
    correctOption: "B" as const,
    explanation:
      "Number of half-lives = 40/10 = 4. Remaining fraction = (1/2)⁴ = 1/16.",
    tags: ["atoms and nuclei", "radioactive decay", "half-life"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Atoms and Nuclei",
    concept: "Nuclear binding energy",
    year: 2021,
    difficulty: "HARD" as const,
    questionText:
      "The binding energy per nucleon is maximum for:",
    optionA: "Hydrogen",
    optionB: "Iron (Fe-56)",
    optionC: "Uranium",
    optionD: "Carbon",
    correctOption: "B" as const,
    explanation:
      "The binding energy per nucleon curve peaks around mass number A ≈ 56 (Iron), indicating it is the most stable nucleus.",
    tags: ["atoms and nuclei", "binding energy", "nuclear stability"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Atoms and Nuclei",
    concept: "Alpha decay",
    year: 2017,
    difficulty: "MEDIUM" as const,
    questionText:
      "In alpha decay, the atomic number of the parent nucleus decreases by:",
    optionA: "1",
    optionB: "2",
    optionC: "4",
    optionD: "0",
    correctOption: "B" as const,
    explanation:
      "An alpha particle (⁴He) carries 2 protons, so Z decreases by 2 and A decreases by 4.",
    tags: ["atoms and nuclei", "alpha decay", "nuclear reactions"],
  },

  // ─── ELECTROMAGNETIC INDUCTION ────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Electromagnetic Induction",
    concept: "Faraday's law",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "The magnetic flux through a coil changes from 0.5 Wb to 0.1 Wb in 0.2 s. The induced emf is:",
    optionA: "2 V",
    optionB: "0.2 V",
    optionC: "20 V",
    optionD: "0.02 V",
    correctOption: "A" as const,
    explanation:
      "EMF = −ΔΦ/Δt = −(0.1 − 0.5)/0.2 = 0.4/0.2 = 2 V.",
    tags: ["electromagnetic induction", "Faraday's law", "induced emf"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electromagnetic Induction",
    concept: "Lenz's law",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "Lenz's law is a consequence of conservation of:",
    optionA: "Charge",
    optionB: "Energy",
    optionC: "Mass",
    optionD: "Momentum",
    correctOption: "B" as const,
    explanation:
      "Lenz's law states that the induced current opposes the cause producing it, consistent with conservation of energy.",
    tags: ["electromagnetic induction", "Lenz's law", "energy conservation"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electromagnetic Induction",
    concept: "Self inductance",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "A coil has self-inductance 2 H. If the current through it changes from 4 A to 0 A in 0.1 s, the induced emf is:",
    optionA: "80 V",
    optionB: "8 V",
    optionC: "0.8 V",
    optionD: "800 V",
    correctOption: "A" as const,
    explanation:
      "EMF = L×(ΔI/Δt) = 2×(4/0.1) = 2×40 = 80 V.",
    tags: ["electromagnetic induction", "self inductance", "solenoid"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electromagnetic Induction",
    concept: "Transformer",
    year: 2024,
    difficulty: "MEDIUM" as const,
    questionText:
      "A step-up transformer has 100 primary turns and 1000 secondary turns. If primary voltage is 220 V, the secondary voltage is:",
    optionA: "22 V",
    optionB: "2200 V",
    optionC: "220 V",
    optionD: "22000 V",
    correctOption: "B" as const,
    explanation:
      "Vs/Vp = Ns/Np → Vs = 220×(1000/100) = 2200 V.",
    tags: ["electromagnetic induction", "transformer", "turns ratio"],
  },

  // ─── OSCILLATIONS AND WAVES ───────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Oscillations and Waves",
    concept: "Simple harmonic motion",
    year: 2016,
    difficulty: "EASY" as const,
    questionText:
      "The time period of a simple pendulum of length 1 m is (g = 10 m/s², π² ≈ 10):",
    optionA: "2 s",
    optionB: "1 s",
    optionC: "4 s",
    optionD: "0.5 s",
    correctOption: "A" as const,
    explanation:
      "T = 2π√(L/g) = 2π√(1/10) = 2π/√10 ≈ 2×3.14/3.16 ≈ 2 s.",
    tags: ["oscillations", "simple pendulum", "time period"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Oscillations and Waves",
    concept: "Wave speed",
    year: 2022,
    difficulty: "EASY" as const,
    questionText:
      "A wave has frequency 500 Hz and wavelength 0.6 m. Its speed is:",
    optionA: "300 m/s",
    optionB: "833 m/s",
    optionC: "0.0012 m/s",
    optionD: "3000 m/s",
    correctOption: "A" as const,
    explanation:
      "v = fλ = 500×0.6 = 300 m/s.",
    tags: ["waves", "wave speed", "frequency wavelength"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Oscillations and Waves",
    concept: "Doppler effect",
    year: 2019,
    difficulty: "HARD" as const,
    questionText:
      "A source of sound moves toward a stationary observer at 10 m/s. The speed of sound is 340 m/s and source frequency is 1000 Hz. The apparent frequency heard by the observer is approximately:",
    optionA: "1030 Hz",
    optionB: "970 Hz",
    optionC: "1000 Hz",
    optionD: "1100 Hz",
    correctOption: "A" as const,
    explanation:
      "f' = f×v/(v − vs) = 1000×340/(340−10) = 340000/330 ≈ 1030 Hz.",
    tags: ["waves", "Doppler effect", "sound"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Oscillations and Waves",
    concept: "Resonance – standing waves",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "A string of length 1 m fixed at both ends vibrates in its fundamental mode. The wavelength of the standing wave is:",
    optionA: "0.5 m",
    optionB: "1 m",
    optionC: "2 m",
    optionD: "4 m",
    correctOption: "C" as const,
    explanation:
      "For fundamental mode (1st harmonic) in a string fixed at both ends: L = λ/2 → λ = 2L = 2×1 = 2 m.",
    tags: ["waves", "standing waves", "resonance"],
  },

  // ─── PROPERTIES OF BULK MATTER ────────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Properties of Bulk Matter",
    concept: "Young's modulus",
    year: 2017,
    difficulty: "MEDIUM" as const,
    questionText:
      "A wire of length 2 m and cross-section area 10⁻⁶ m² stretches by 1 mm when a force of 100 N is applied. Young's modulus of the wire is:",
    optionA: "2×10¹¹ Pa",
    optionB: "2×10⁸ Pa",
    optionC: "2×10¹⁰ Pa",
    optionD: "2×10⁹ Pa",
    correctOption: "A" as const,
    explanation:
      "Y = FL/(AΔL) = 100×2/(10⁻⁶×10⁻³) = 200/10⁻⁹ = 2×10¹¹ Pa.",
    tags: ["properties of bulk matter", "Young's modulus", "elasticity"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Properties of Bulk Matter",
    concept: "Surface tension",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "Excess pressure inside a soap bubble of radius r with surface tension T is:",
    optionA: "T/r",
    optionB: "2T/r",
    optionC: "4T/r",
    optionD: "T/2r",
    correctOption: "C" as const,
    explanation:
      "A soap bubble has two surfaces. Excess pressure = 4T/r (factor of 2 from each surface compared to a liquid drop which has 2T/r).",
    tags: ["properties of bulk matter", "surface tension", "bubble"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Properties of Bulk Matter",
    concept: "Viscosity – Stokes' law",
    year: 2023,
    difficulty: "HARD" as const,
    questionText:
      "A small sphere falls through a viscous liquid. At terminal velocity, the viscous drag force on the sphere is equal to:",
    optionA: "Weight of sphere",
    optionB: "Weight of sphere minus buoyant force",
    optionC: "Buoyant force only",
    optionD: "Zero",
    correctOption: "B" as const,
    explanation:
      "At terminal velocity, net downward force = 0: Weight = Buoyant force + Viscous drag → Drag = Weight − Buoyant force.",
    tags: ["properties of bulk matter", "viscosity", "terminal velocity", "Stokes' law"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Properties of Bulk Matter",
    concept: "Bernoulli's theorem",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "Bernoulli's theorem is based on conservation of:",
    optionA: "Mass",
    optionB: "Momentum",
    optionC: "Energy",
    optionD: "Angular momentum",
    correctOption: "C" as const,
    explanation:
      "Bernoulli's principle is derived from the work-energy theorem and represents conservation of energy for fluid flow.",
    tags: ["properties of bulk matter", "Bernoulli's theorem", "fluid dynamics"],
  },

  // ─── ADDITIONAL MIXED QUESTIONS ───────────────────────────────────────────
  {
    subject: "PHYSICS" as const,
    chapter: "Electrostatics",
    concept: "Energy stored in capacitor",
    year: 2024,
    difficulty: "MEDIUM" as const,
    questionText:
      "A capacitor of 10 μF is charged to 100 V. The energy stored in it is:",
    optionA: "0.05 J",
    optionB: "0.5 J",
    optionC: "5 J",
    optionD: "50 J",
    correctOption: "A" as const,
    explanation:
      "U = ½CV² = ½×10×10⁻⁶×(100)² = ½×10×10⁻⁶×10⁴ = 0.05 J.",
    tags: ["electrostatics", "capacitor", "energy stored"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Current Electricity",
    concept: "EMF and internal resistance",
    year: 2015,
    difficulty: "MEDIUM" as const,
    questionText:
      "A battery of EMF 12 V and internal resistance 1 Ω is connected to an external resistance of 5 Ω. The terminal voltage is:",
    optionA: "10 V",
    optionB: "12 V",
    optionC: "2 V",
    optionD: "11 V",
    correctOption: "A" as const,
    explanation:
      "I = EMF/(R+r) = 12/6 = 2 A. Terminal voltage = EMF − Ir = 12 − 2×1 = 10 V.",
    tags: ["current electricity", "EMF", "internal resistance"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Magnifying power – microscope",
    year: 2017,
    difficulty: "HARD" as const,
    questionText:
      "The magnifying power of a simple microscope with focal length 5 cm (for normal adjustment, D = 25 cm) is:",
    optionA: "5",
    optionB: "6",
    optionC: "25",
    optionD: "1",
    correctOption: "B" as const,
    explanation:
      "For simple microscope: m = 1 + D/f = 1 + 25/5 = 1 + 5 = 6.",
    tags: ["optics", "microscope", "magnifying power"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Atoms and Nuclei",
    concept: "de Broglie wavelength",
    year: 2022,
    difficulty: "HARD" as const,
    questionText:
      "The de Broglie wavelength of an electron (mass 9.1×10⁻³¹ kg) moving at 10⁶ m/s is approximately (h = 6.6×10⁻³⁴ J·s):",
    optionA: "0.73 nm",
    optionB: "7.3 nm",
    optionC: "0.073 nm",
    optionD: "73 nm",
    correctOption: "A" as const,
    explanation:
      "λ = h/(mv) = 6.6×10⁻³⁴/(9.1×10⁻³¹×10⁶) = 6.6×10⁻³⁴/9.1×10⁻²⁵ ≈ 0.73×10⁻⁹ m = 0.73 nm.",
    tags: ["atoms and nuclei", "de Broglie wavelength", "wave-particle duality"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electromagnetic Induction",
    concept: "AC circuits – resonance",
    year: 2020,
    difficulty: "HARD" as const,
    questionText:
      "In an LCR series circuit, resonance occurs when:",
    optionA: "XL = XC",
    optionB: "XL > XC",
    optionC: "R = XL",
    optionD: "R = XC",
    correctOption: "A" as const,
    explanation:
      "At resonance in a series LCR circuit, inductive reactance equals capacitive reactance (XL = XC), and impedance is minimum (= R).",
    tags: ["electromagnetic induction", "AC circuits", "resonance", "LCR"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Oscillations and Waves",
    concept: "SHM – energy",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "For a body executing SHM, the total mechanical energy is:",
    optionA: "½mω²A² at any position",
    optionB: "Maximum at extreme position and minimum at mean position",
    optionC: "Varies with time",
    optionD: "Zero at mean position",
    correctOption: "A" as const,
    explanation:
      "Total energy in SHM = ½mω²A² = constant (A = amplitude), independent of position. KE and PE interchange but total stays constant.",
    tags: ["oscillations", "SHM", "energy", "amplitude"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Circular motion – angular velocity",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "A particle completes 5 revolutions per second in circular motion. Its angular velocity is:",
    optionA: "5 rad/s",
    optionB: "10π rad/s",
    optionC: "2π rad/s",
    optionD: "5π rad/s",
    correctOption: "B" as const,
    explanation:
      "ω = 2πn = 2π×5 = 10π rad/s.",
    tags: ["kinematics", "circular motion", "angular velocity"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Laws of Motion",
    concept: "Free body diagram",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "Two blocks of mass 3 kg and 5 kg are connected by a string and placed on a frictionless surface. A force of 16 N is applied on the 5 kg block. The tension in the string is:",
    optionA: "6 N",
    optionB: "10 N",
    optionC: "16 N",
    optionD: "4 N",
    correctOption: "A" as const,
    explanation:
      "Total mass = 8 kg; a = F/m_total = 16/8 = 2 m/s². Tension acts on 3 kg block: T = 3×a = 3×2 = 6 N.",
    tags: ["laws of motion", "tension", "Newton's second law", "system of blocks"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Thermodynamics",
    concept: "Adiabatic process",
    year: 2016,
    difficulty: "HARD" as const,
    questionText:
      "For an ideal gas undergoing an adiabatic process, which relation holds (γ = Cp/Cv)?",
    optionA: "PV = constant",
    optionB: "PVγ = constant",
    optionC: "TV = constant",
    optionD: "PγV = constant",
    correctOption: "B" as const,
    explanation:
      "In an adiabatic process (no heat exchange), PVγ = constant where γ = Cp/Cv.",
    tags: ["thermodynamics", "adiabatic", "ideal gas", "gamma"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Gravitation",
    concept: "Variation of g with altitude",
    year: 2018,
    difficulty: "MEDIUM" as const,
    questionText:
      "The value of g at a height h above Earth's surface is related to surface value g₀ by (R = Earth's radius):",
    optionA: "g₀(1 − h/R)",
    optionB: "g₀R²/(R+h)²",
    optionC: "g₀(R+h)²/R²",
    optionD: "g₀(1 + h/R)",
    correctOption: "B" as const,
    explanation:
      "g = GM/(R+h)² = g₀R²/(R+h)², since g₀ = GM/R².",
    tags: ["gravitation", "g variation", "altitude"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Work Energy Power",
    concept: "Work-energy theorem",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "A body of mass 2 kg is moving at 5 m/s. A force acts on it and its velocity becomes 9 m/s. The work done by the force is:",
    optionA: "28 J",
    optionB: "56 J",
    optionC: "81 J",
    optionD: "25 J",
    correctOption: "B" as const,
    explanation:
      "W = ΔKE = ½m(v² − u²) = ½×2×(81−25) = 1×56 = 56 J.",
    tags: ["work energy power", "work-energy theorem", "kinetic energy"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Optics",
    concept: "Dispersion of light",
    year: 2014,
    difficulty: "EASY" as const,
    questionText:
      "When white light passes through a glass prism, the colour that deviates the most is:",
    optionA: "Red",
    optionB: "Yellow",
    optionC: "Green",
    optionD: "Violet",
    correctOption: "D" as const,
    explanation:
      "Violet light has the shortest wavelength, travels slowest in glass (highest refractive index), and thus deviates the most. Red deviates the least (VIBGYOR order of deviation).",
    tags: ["optics", "dispersion", "prism", "VIBGYOR"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Current Electricity",
    concept: "Cells in series and parallel",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "Two cells each of EMF 1.5 V and internal resistance 1 Ω are connected in series to an external resistance of 4 Ω. The current in the circuit is:",
    optionA: "0.5 A",
    optionB: "0.75 A",
    optionC: "1.5 A",
    optionD: "3 A",
    correctOption: "A" as const,
    explanation:
      "Total EMF = 1.5+1.5 = 3 V; total internal resistance = 2 Ω; I = 3/(4+2) = 3/6 = 0.5 A.",
    tags: ["current electricity", "cells in series", "EMF"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electromagnetic Induction",
    concept: "Eddy currents",
    year: 2021,
    difficulty: "EASY" as const,
    questionText:
      "Eddy currents are minimized in transformer cores by:",
    optionA: "Using thick iron cores",
    optionB: "Using laminated iron cores",
    optionC: "Using copper cores",
    optionD: "Increasing the number of turns",
    correctOption: "B" as const,
    explanation:
      "Laminated cores break up the path for eddy currents, greatly reducing their magnitude and associated energy losses.",
    tags: ["electromagnetic induction", "eddy currents", "transformer"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Properties of Bulk Matter",
    concept: "Capillarity",
    year: 2014,
    difficulty: "EASY" as const,
    questionText:
      "The rise of liquid in a capillary tube is inversely proportional to:",
    optionA: "Surface tension",
    optionB: "Radius of capillary",
    optionC: "Density of liquid",
    optionD: "cos θ (contact angle)",
    correctOption: "B" as const,
    explanation:
      "h = 2T cosθ/(ρgr). Height h ∝ 1/r — a narrower capillary gives greater rise.",
    tags: ["properties of bulk matter", "capillarity", "surface tension"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Atoms and Nuclei",
    concept: "Photoelectric effect",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "In the photoelectric effect, the kinetic energy of emitted photoelectrons depends on:",
    optionA: "Intensity of incident light",
    optionB: "Frequency of incident light",
    optionC: "Both intensity and frequency",
    optionD: "Neither intensity nor frequency",
    correctOption: "B" as const,
    explanation:
      "KE_max = hf − φ (Einstein's equation). KE depends on frequency, NOT intensity. Intensity affects the number of electrons emitted.",
    tags: ["atoms and nuclei", "photoelectric effect", "Einstein's equation"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Oscillations and Waves",
    concept: "Beats",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "Two tuning forks produce 4 beats per second. If one fork has frequency 256 Hz, the frequency of the other can be:",
    optionA: "260 or 252 Hz",
    optionB: "256 Hz",
    optionC: "512 Hz",
    optionD: "128 Hz",
    correctOption: "A" as const,
    explanation:
      "Beat frequency = |f₁ − f₂|. So f₂ = 256 ± 4 = 260 or 252 Hz.",
    tags: ["waves", "beats", "tuning fork"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Kinematics",
    concept: "Uniform circular motion",
    year: 2024,
    difficulty: "MEDIUM" as const,
    questionText:
      "A stone tied to a string is whirled in a horizontal circle of radius 0.5 m with speed 2 m/s. The centripetal acceleration is:",
    optionA: "8 m/s²",
    optionB: "4 m/s²",
    optionC: "2 m/s²",
    optionD: "1 m/s²",
    correctOption: "A" as const,
    explanation:
      "ac = v²/r = (2)²/0.5 = 4/0.5 = 8 m/s².",
    tags: ["kinematics", "circular motion", "centripetal acceleration"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Thermodynamics",
    concept: "Kinetic theory of gases",
    year: 2019,
    difficulty: "HARD" as const,
    questionText:
      "The rms speed of molecules of an ideal gas is proportional to:",
    optionA: "√T",
    optionB: "T",
    optionC: "T²",
    optionD: "1/√T",
    correctOption: "A" as const,
    explanation:
      "v_rms = √(3RT/M) ∝ √T. The rms speed of gas molecules is directly proportional to the square root of temperature.",
    tags: ["thermodynamics", "kinetic theory", "rms speed"],
  },
  {
    subject: "PHYSICS" as const,
    chapter: "Electrostatics",
    concept: "Dipole in uniform field",
    year: 2016,
    difficulty: "HARD" as const,
    questionText:
      "An electric dipole placed in a uniform electric field experiences:",
    optionA: "A net force and a torque",
    optionB: "A net force only",
    optionC: "A torque only",
    optionD: "Neither force nor torque",
    correctOption: "C" as const,
    explanation:
      "In a uniform field, equal and opposite forces act on +q and −q charges, giving zero net force but a net torque τ = pE sinθ.",
    tags: ["electrostatics", "electric dipole", "torque"],
  },
];
