export const zoologyQuestions = [
  // ─── ANIMAL KINGDOM ───────────────────────────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Classification – Porifera",
    year: 2016,
    difficulty: "EASY" as const,
    questionText:
      "Sponges (Phylum Porifera) are characterized by the presence of:",
    optionA: "Cnidoblasts",
    optionB: "Choanocytes (collar cells)",
    optionC: "Trochophore larva",
    optionD: "Nematocysts",
    correctOption: "B" as const,
    explanation:
      "Porifera (sponges) are unique in having choanocytes (collar cells) that line the spongocoel and create water currents by flagellar movement, trapping food particles.",
    tags: ["animal kingdom", "Porifera", "choanocytes", "sponges"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Classification – Coelenterata",
    year: 2019,
    difficulty: "EASY" as const,
    questionText:
      "Cnidoblasts (nematocysts) are characteristic of which phylum?",
    optionA: "Platyhelminthes",
    optionB: "Coelenterata (Cnidaria)",
    optionC: "Porifera",
    optionD: "Echinodermata",
    correctOption: "B" as const,
    explanation:
      "Cnidoblasts are stinging cells containing nematocysts, unique to Cnidaria (Coelenterata). They are used for defense and prey capture. Examples: Hydra, Jellyfish, Corals.",
    tags: ["animal kingdom", "Cnidaria", "cnidoblasts", "nematocysts"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Body symmetry",
    year: 2021,
    difficulty: "EASY" as const,
    questionText:
      "Echinoderms (starfish, sea urchins) show which type of symmetry in adults?",
    optionA: "Bilateral symmetry",
    optionB: "Radial symmetry",
    optionC: "Pentamerous (5-fold) radial symmetry",
    optionD: "Asymmetry",
    correctOption: "C" as const,
    explanation:
      "Adult echinoderms show pentamerous (5-fold) radial symmetry. Interestingly, their larvae are bilaterally symmetrical, and they are more closely related to vertebrates than other invertebrates.",
    tags: ["animal kingdom", "Echinodermata", "pentamerous symmetry"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Classification – Annelida",
    year: 2018,
    difficulty: "MEDIUM" as const,
    questionText:
      "Which of the following is the characteristic feature of Annelida?",
    optionA: "Pseudocoelom",
    optionB: "Metamerism (true segmentation) with true coelom",
    optionC: "Open circulatory system",
    optionD: "No excretory organs",
    correctOption: "B" as const,
    explanation:
      "Annelids (earthworms, leeches, polychaetes) have true metamerism (body divided into segments externally and internally), true coelom (schizocoel), and a closed circulatory system.",
    tags: ["animal kingdom", "Annelida", "metamerism", "coelom"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Classification – Chordata",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "Which of the following is NOT a fundamental characteristic of Phylum Chordata?",
    optionA: "Notochord",
    optionB: "Dorsal hollow nerve cord",
    optionC: "Pharyngeal gill slits",
    optionD: "Ventral heart",
    correctOption: "D" as const,
    explanation:
      "The three fundamental chordate characters are: (1) notochord, (2) dorsal hollow nerve cord, (3) pharyngeal gill slits (post-anal tail is also included). A ventral heart is a vertebrate feature, not exclusive to all chordates.",
    tags: ["animal kingdom", "Chordata", "notochord", "nerve cord"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Arthropoda features",
    year: 2017,
    difficulty: "MEDIUM" as const,
    questionText:
      "Arthropoda is the largest phylum in the animal kingdom. They possess:",
    optionA: "Soft unsegmented body",
    optionB: "Jointed appendages and exoskeleton of chitin",
    optionC: "Water vascular system",
    optionD: "Endoskeleton of bone",
    correctOption: "B" as const,
    explanation:
      "The defining features of Arthropoda are jointed appendages (arthron = joint, poda = feet), a chitinous exoskeleton, segmented body, and open circulatory system.",
    tags: ["animal kingdom", "Arthropoda", "jointed appendages", "chitin"],
  },

  // ─── HUMAN PHYSIOLOGY: DIGESTION AND ABSORPTION ───────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Digestion)",
    concept: "Digestive enzymes",
    year: 2016,
    difficulty: "EASY" as const,
    questionText:
      "Salivary amylase (ptyalin) in the mouth begins the digestion of:",
    optionA: "Proteins",
    optionB: "Fats",
    optionC: "Starch (carbohydrates)",
    optionD: "Nucleic acids",
    correctOption: "C" as const,
    explanation:
      "Salivary amylase hydrolyzes starch (polysaccharides) into maltose and dextrins. It requires slightly alkaline/neutral pH and is inactivated by the stomach's HCl.",
    tags: ["digestion", "salivary amylase", "starch", "mouth"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Digestion)",
    concept: "Stomach",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "The enzyme pepsin acts in the stomach to digest proteins. It is secreted as an inactive precursor called:",
    optionA: "Pepsinogen",
    optionB: "Trypsinogen",
    optionC: "Chymotrypsinogen",
    optionD: "Proenzyme",
    correctOption: "A" as const,
    explanation:
      "Chief cells of the stomach secrete pepsinogen (inactive). HCl from parietal cells converts pepsinogen → pepsin (active). Pepsin then digests proteins into peptones and proteoses.",
    tags: ["digestion", "pepsin", "pepsinogen", "stomach", "zymogen"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Digestion)",
    concept: "Small intestine",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "Bile salts produced by the liver and stored in the gall bladder help in:",
    optionA: "Protein digestion",
    optionB: "Emulsification of fats",
    optionC: "Carbohydrate digestion",
    optionD: "Absorption of vitamins B and C",
    correctOption: "B" as const,
    explanation:
      "Bile salts (not enzymes) emulsify large fat droplets into smaller ones, increasing the surface area for lipase action. They also help in absorption of fat-soluble vitamins (A, D, E, K).",
    tags: ["digestion", "bile salts", "emulsification", "fat digestion"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Digestion)",
    concept: "Absorption",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "Absorption of glucose and amino acids across the intestinal epithelium occurs mainly by:",
    optionA: "Simple diffusion",
    optionB: "Osmosis",
    optionC: "Active transport (Na⁺ cotransport)",
    optionD: "Endocytosis",
    correctOption: "C" as const,
    explanation:
      "Glucose and amino acids are absorbed by secondary active transport – co-transported with Na⁺ ions down the Na⁺ gradient (established by Na⁺/K⁺-ATPase). This is sodium-dependent active transport.",
    tags: ["digestion", "absorption", "active transport", "glucose", "Na+ cotransport"],
  },

  // ─── HUMAN PHYSIOLOGY: BREATHING AND GAS EXCHANGE ─────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Breathing)",
    concept: "Lung volumes",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "The volume of air remaining in the lungs after maximum forced expiration is called:",
    optionA: "Tidal Volume",
    optionB: "Residual Volume (RV)",
    optionC: "Expiratory Reserve Volume",
    optionD: "Vital Capacity",
    correctOption: "B" as const,
    explanation:
      "Residual Volume (RV) ≈ 1200 mL is the volume that cannot be expelled. It keeps the alveoli from collapsing. Vital capacity (VC) = IRV + TV + ERV ≈ 4500 mL.",
    tags: ["breathing", "lung volumes", "residual volume", "spirometry"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Breathing)",
    concept: "Haemoglobin oxygen transport",
    year: 2018,
    difficulty: "MEDIUM" as const,
    questionText:
      "The oxygen-dissociation curve shifts to the right (Bohr effect) when:",
    optionA: "pH increases",
    optionB: "CO₂ decreases",
    optionC: "Temperature increases or pH decreases",
    optionD: "pO₂ increases",
    correctOption: "C" as const,
    explanation:
      "The Bohr effect: increased CO₂ (→ decreased pH) or increased temperature reduces Hb's affinity for O₂, shifting the curve right → promotes O₂ release to active tissues.",
    tags: ["breathing", "haemoglobin", "Bohr effect", "oxygen dissociation curve"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Breathing)",
    concept: "CO2 transport",
    year: null,
    difficulty: "HARD" as const,
    questionText:
      "The majority of CO₂ transported in blood is in the form of:",
    optionA: "Dissolved CO₂",
    optionB: "Carbaminohaemoglobin",
    optionC: "Bicarbonate ions (HCO₃⁻)",
    optionD: "CO₂-albumin complex",
    correctOption: "C" as const,
    explanation:
      "~70% of CO₂ is transported as HCO₃⁻ (bicarbonate ions) in plasma. ~23% as carbaminohaemoglobin. ~7% dissolved in plasma.",
    tags: ["breathing", "CO2 transport", "bicarbonate", "Haldane effect"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Breathing)",
    concept: "Breathing mechanics",
    year: 2024,
    difficulty: "EASY" as const,
    questionText:
      "During inspiration (inhalation), the diaphragm:",
    optionA: "Relaxes and moves upward",
    optionB: "Contracts and moves downward",
    optionC: "Does not move",
    optionD: "Contracts and moves upward",
    correctOption: "B" as const,
    explanation:
      "During inspiration, the diaphragm contracts and flattens (moves downward), increasing thoracic volume. This decreases intrapulmonary pressure below atmospheric pressure, drawing air in.",
    tags: ["breathing", "inspiration", "diaphragm", "mechanics"],
  },

  // ─── HUMAN PHYSIOLOGY: BODY FLUIDS AND CIRCULATION ───────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Circulation)",
    concept: "Blood components",
    year: 2017,
    difficulty: "EASY" as const,
    questionText:
      "The universal blood donor blood group is:",
    optionA: "A",
    optionB: "B",
    optionC: "AB",
    optionD: "O",
    correctOption: "D" as const,
    explanation:
      "Blood group O (O negative) is the universal donor because RBCs lack A and B antigens. Blood group AB is the universal recipient (lacks anti-A and anti-B antibodies in plasma).",
    tags: ["circulation", "blood groups", "ABO system", "universal donor"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Circulation)",
    concept: "Cardiac cycle",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "The 'lub' sound of the heartbeat is produced by:",
    optionA: "Opening of semilunar valves",
    optionB: "Closure of atrioventricular (AV) valves",
    optionC: "Closure of semilunar valves",
    optionD: "Opening of AV valves",
    correctOption: "B" as const,
    explanation:
      "The first heart sound 'lub' (S1) is produced by closure of the mitral (bicuspid) and tricuspid AV valves at the beginning of ventricular systole. The 'dub' (S2) is from semilunar valve closure.",
    tags: ["circulation", "cardiac cycle", "heart sounds", "valves"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Circulation)",
    concept: "Cardiac output",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "Cardiac output = Heart rate × Stroke volume. If heart rate is 72 beats/min and stroke volume is 70 mL, cardiac output is:",
    optionA: "5040 mL/min (≈5 L/min)",
    optionB: "142 mL/min",
    optionC: "7200 mL/min",
    optionD: "1.03 mL/min",
    correctOption: "A" as const,
    explanation:
      "CO = HR × SV = 72 × 70 = 5040 mL/min ≈ 5 L/min. This is the normal resting cardiac output.",
    tags: ["circulation", "cardiac output", "stroke volume", "heart rate"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Circulation)",
    concept: "Erythrocytes",
    year: 2015,
    difficulty: "EASY" as const,
    questionText:
      "Mature human red blood cells (RBCs) lack a nucleus. The average lifespan of an RBC is approximately:",
    optionA: "10 days",
    optionB: "60 days",
    optionC: "120 days",
    optionD: "1 year",
    correctOption: "C" as const,
    explanation:
      "Human RBCs live for approximately 120 days. After this, they are destroyed in the spleen (graveyard of RBCs). They are continuously replaced by erythropoiesis in red bone marrow.",
    tags: ["circulation", "RBC", "erythrocyte", "lifespan"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Circulation)",
    concept: "Lymphatic system",
    year: null,
    difficulty: "MEDIUM" as const,
    questionText:
      "The thoracic duct (largest lymphatic vessel) drains lymph into the:",
    optionA: "Right subclavian vein",
    optionB: "Left subclavian vein at the junction with jugular vein",
    optionC: "Portal vein",
    optionD: "Inferior vena cava",
    correctOption: "B" as const,
    explanation:
      "The thoracic duct collects lymph from most of the body and drains it into the left subclavian vein (at the junction with the left internal jugular vein).",
    tags: ["circulation", "lymph", "thoracic duct", "lymphatic system"],
  },

  // ─── HUMAN PHYSIOLOGY: EXCRETION ──────────────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Excretion)",
    concept: "Nephron structure",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "The process of glomerular filtration (ultrafiltration) in the kidney occurs at the:",
    optionA: "Bowman's capsule and glomerulus (renal corpuscle)",
    optionB: "Proximal convoluted tubule (PCT)",
    optionC: "Loop of Henle",
    optionD: "Collecting duct",
    correctOption: "A" as const,
    explanation:
      "Ultrafiltration occurs at the renal corpuscle (Bowman's capsule + glomerulus). High blood pressure in the glomerulus forces water, ions, glucose, urea, etc. into Bowman's space. Large proteins and cells remain in blood.",
    tags: ["excretion", "nephron", "glomerular filtration", "Bowman's capsule"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Excretion)",
    concept: "Tubular reabsorption",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "Approximately what percentage of the glomerular filtrate (GFR ~180 L/day) is reabsorbed?",
    optionA: "50%",
    optionB: "75%",
    optionC: "99%",
    optionD: "90%",
    correctOption: "C" as const,
    explanation:
      "~180 L/day is filtered; ~1.5-2 L/day is excreted as urine. Thus ~99% is reabsorbed. Most reabsorption (67%) occurs in the PCT.",
    tags: ["excretion", "reabsorption", "GFR", "urine formation"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Excretion)",
    concept: "ADH and osmoregulation",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "Antidiuretic hormone (ADH/vasopressin) acts on the kidney to:",
    optionA: "Increase urine volume",
    optionB: "Decrease water reabsorption in the collecting duct",
    optionC: "Increase water reabsorption in the collecting duct, decreasing urine volume",
    optionD: "Increase Na⁺ excretion",
    correctOption: "C" as const,
    explanation:
      "ADH (from posterior pituitary) increases the permeability of the collecting duct to water by inserting aquaporin channels, promoting water reabsorption and producing concentrated urine. Alcohol inhibits ADH → diuresis.",
    tags: ["excretion", "ADH", "vasopressin", "osmoregulation", "aquaporin"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Excretion)",
    concept: "Urea formation",
    year: 2016,
    difficulty: "HARD" as const,
    questionText:
      "Urea is synthesized in the liver via the ornithine cycle (urea cycle). The immediate precursor that combines with CO₂ and NH₃ to start the cycle is:",
    optionA: "Ornithine",
    optionB: "Citrulline",
    optionC: "Arginine",
    optionD: "Carbamoyl phosphate",
    correctOption: "A" as const,
    explanation:
      "The urea cycle: Ornithine + carbamoyl phosphate → Citrulline → Argininosuccinate → Arginine → Ornithine + Urea. Ornithine is regenerated in each cycle turn.",
    tags: ["excretion", "urea cycle", "ornithine", "liver"],
  },

  // ─── HUMAN PHYSIOLOGY: NEURAL CONTROL AND COORDINATION ───────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Neural Control)",
    concept: "Neuron structure",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "The myelin sheath in peripheral nerves is formed by:",
    optionA: "Astrocytes",
    optionB: "Microglia",
    optionC: "Schwann cells",
    optionD: "Oligodendrocytes",
    correctOption: "C" as const,
    explanation:
      "In the PNS, Schwann cells form the myelin sheath by wrapping around axons. In the CNS, oligodendrocytes form myelin. Nodes of Ranvier are gaps between Schwann cells.",
    tags: ["neural control", "myelin sheath", "Schwann cells", "neuron"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Neural Control)",
    concept: "Action potential",
    year: 2020,
    difficulty: "HARD" as const,
    questionText:
      "During an action potential, the depolarization phase occurs due to:",
    optionA: "Rapid influx of K⁺ ions",
    optionB: "Efflux of Na⁺ ions",
    optionC: "Rapid influx of Na⁺ ions through voltage-gated channels",
    optionD: "Influx of Cl⁻ ions",
    correctOption: "C" as const,
    explanation:
      "Depolarization: voltage-gated Na⁺ channels open → Na⁺ rushes in → membrane potential reverses to +40 mV. Repolarization: K⁺ channels open → K⁺ flows out. Na⁺/K⁺ pump restores resting potential.",
    tags: ["neural control", "action potential", "depolarization", "Na+ influx"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Neural Control)",
    concept: "Synapse and neurotransmitters",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "Acetylcholine (ACh) is the neurotransmitter at the neuromuscular junction. It is broken down by the enzyme:",
    optionA: "MAO (monoamine oxidase)",
    optionB: "Acetylcholinesterase",
    optionC: "Cholineacetyltransferase",
    optionD: "Tyrosine hydroxylase",
    correctOption: "B" as const,
    explanation:
      "Acetylcholinesterase breaks down ACh into acetate and choline in the synaptic cleft, terminating the signal. Choline is recycled back into the presynaptic terminal.",
    tags: ["neural control", "neurotransmitter", "acetylcholine", "acetylcholinesterase"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Neural Control)",
    concept: "Brain – regions",
    year: 2017,
    difficulty: "MEDIUM" as const,
    questionText:
      "The 'seat of intelligence', memory, and voluntary actions in the brain is the:",
    optionA: "Cerebellum",
    optionB: "Medulla oblongata",
    optionC: "Cerebrum (cerebral cortex)",
    optionD: "Hypothalamus",
    correctOption: "C" as const,
    explanation:
      "The cerebrum (especially the frontal lobe) is associated with intelligence, reasoning, memory, and voluntary movements. Cerebellum coordinates movement; medulla controls vital reflexes.",
    tags: ["neural control", "cerebrum", "intelligence", "brain"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Neural Control)",
    concept: "Reflex arc",
    year: null,
    difficulty: "EASY" as const,
    questionText:
      "The correct sequence of a reflex arc is:",
    optionA: "Effector → Afferent nerve → Nerve centre → Efferent nerve → Receptor",
    optionB: "Receptor → Afferent nerve → Nerve centre → Efferent nerve → Effector",
    optionC: "Receptor → Efferent nerve → Nerve centre → Afferent nerve → Effector",
    optionD: "Effector → Efferent nerve → Nerve centre → Afferent nerve → Receptor",
    correctOption: "B" as const,
    explanation:
      "Reflex arc: Receptor (detects stimulus) → Sensory/Afferent neuron → Nerve centre (spinal cord or brain) → Motor/Efferent neuron → Effector (muscle/gland).",
    tags: ["neural control", "reflex arc", "afferent", "efferent"],
  },

  // ─── HUMAN PHYSIOLOGY: ENDOCRINE SYSTEM ──────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Endocrine)",
    concept: "Insulin and glucagon",
    year: 2019,
    difficulty: "EASY" as const,
    questionText:
      "Insulin is secreted by which cells of the islets of Langerhans in the pancreas?",
    optionA: "Alpha cells",
    optionB: "Beta cells",
    optionC: "Delta cells",
    optionD: "Acinar cells",
    correctOption: "B" as const,
    explanation:
      "Beta (β) cells of islets of Langerhans secrete insulin, which lowers blood glucose. Alpha (α) cells secrete glucagon (raises blood glucose). Delta cells secrete somatostatin.",
    tags: ["endocrine", "insulin", "beta cells", "pancreas", "islets of Langerhans"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Endocrine)",
    concept: "Thyroid hormones",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "Iodine is an essential component of thyroid hormones. Deficiency of iodine leads to:",
    optionA: "Diabetes mellitus",
    optionB: "Goitre (enlarged thyroid gland)",
    optionC: "Addison's disease",
    optionD: "Acromegaly",
    correctOption: "B" as const,
    explanation:
      "Iodine deficiency → reduced T3 and T4 production → increased TSH from pituitary → thyroid hyperplasia → goitre. Cretinism occurs if deficiency is during fetal/early childhood development.",
    tags: ["endocrine", "thyroid", "iodine deficiency", "goitre"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Endocrine)",
    concept: "Adrenal gland",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "The 'fight or flight' response is mediated by hormones secreted by the:",
    optionA: "Adrenal cortex",
    optionB: "Adrenal medulla",
    optionC: "Thyroid gland",
    optionD: "Posterior pituitary",
    correctOption: "B" as const,
    explanation:
      "The adrenal medulla (modified neural tissue) secretes epinephrine (adrenaline) and norepinephrine in response to stress, triggering the 'fight or flight' response. The cortex secretes steroids (cortisol, aldosterone).",
    tags: ["endocrine", "adrenal medulla", "adrenaline", "fight or flight"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Endocrine)",
    concept: "Pituitary gland",
    year: 2024,
    difficulty: "HARD" as const,
    questionText:
      "Growth hormone (GH) is secreted by the anterior pituitary. Excess GH secretion after closure of epiphyseal plates (in adults) causes:",
    optionA: "Gigantism",
    optionB: "Dwarfism",
    optionC: "Acromegaly",
    optionD: "Cretinism",
    correctOption: "C" as const,
    explanation:
      "Excess GH in adults (after bone growth plates fuse) causes acromegaly – enlargement of hands, feet, jaw, and facial features. Excess GH before growth plate fusion causes gigantism.",
    tags: ["endocrine", "growth hormone", "acromegaly", "pituitary"],
  },

  // ─── HUMAN REPRODUCTION ───────────────────────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Reproduction",
    concept: "Spermatogenesis",
    year: 2018,
    difficulty: "MEDIUM" as const,
    questionText:
      "The correct sequence of spermatogenesis is:",
    optionA: "Spermatogonia → Spermatocyte I → Spermatocyte II → Spermatid → Sperm",
    optionB: "Spermatogonia → Spermatid → Spermatocyte I → Spermatocyte II → Sperm",
    optionC: "Spermatocyte I → Spermatogonia → Spermatocyte II → Sperm",
    optionD: "Spermatid → Spermatogonia → Spermatocyte I → Sperm",
    correctOption: "A" as const,
    explanation:
      "Spermatogenesis: Spermatogonia (2n) → Primary spermatocyte (2n, after DNA replication) → Secondary spermatocytes (n, after meiosis I) → Spermatids (n, after meiosis II) → Spermatozoa (after spermiogenesis).",
    tags: ["reproduction", "spermatogenesis", "meiosis", "testes"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Reproduction",
    concept: "Menstrual cycle",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "The corpus luteum in the ovary is responsible for secreting:",
    optionA: "FSH",
    optionB: "LH",
    optionC: "Progesterone (and estrogen)",
    optionD: "hCG",
    correctOption: "C" as const,
    explanation:
      "After ovulation, the ruptured Graafian follicle becomes the corpus luteum, which secretes progesterone (mainly) and some estrogen. Progesterone maintains the uterine endometrium for implantation.",
    tags: ["reproduction", "corpus luteum", "progesterone", "menstrual cycle"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Reproduction",
    concept: "Fertilization and implantation",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "Fertilization (union of sperm and ovum) normally occurs in the:",
    optionA: "Uterus",
    optionB: "Cervix",
    optionC: "Ampullary-isthmic junction of the fallopian tube",
    optionD: "Vagina",
    correctOption: "C" as const,
    explanation:
      "Fertilization occurs in the ampullary region (ampullary-isthmic junction) of the Fallopian tube. The fertilized egg (zygote) then travels to the uterus for implantation at the blastocyst stage.",
    tags: ["reproduction", "fertilization", "fallopian tube", "ampulla"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Reproduction",
    concept: "Embryonic development",
    year: 2016,
    difficulty: "HARD" as const,
    questionText:
      "The process by which cells of the morula differentiate to form blastocyst with an inner cell mass and trophoblast is:",
    optionA: "Cleavage",
    optionB: "Blastulation",
    optionC: "Gastrulation",
    optionD: "Organogenesis",
    correctOption: "B" as const,
    explanation:
      "Blastulation: the morula develops a fluid-filled cavity (blastocoel), forming the blastocyst. The inner cell mass (ICM/embryoblast) gives rise to the embryo; the trophoblast forms the placenta.",
    tags: ["reproduction", "embryonic development", "blastulation", "blastocyst"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Reproduction",
    concept: "Placenta",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "Human Chorionic Gonadotropin (hCG) secreted by the placenta is important because it:",
    optionA: "Stimulates milk production",
    optionB: "Maintains the corpus luteum during early pregnancy",
    optionC: "Causes uterine contractions during labour",
    optionD: "Promotes bone development in fetus",
    correctOption: "B" as const,
    explanation:
      "hCG, secreted by the trophoblast/placenta, rescues the corpus luteum from regression, maintaining progesterone production essential for pregnancy. hCG is detected in pregnancy tests.",
    tags: ["reproduction", "hCG", "placenta", "corpus luteum"],
  },

  // ─── HEALTH AND DISEASE ───────────────────────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Health and Disease",
    concept: "Immunity",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "Vaccines provide immunity by stimulating:",
    optionA: "Passive immunity (transfer of antibodies)",
    optionB: "Active immunity (own immune response and memory cells)",
    optionC: "Non-specific innate immunity only",
    optionD: "Tolerance to pathogens",
    correctOption: "B" as const,
    explanation:
      "Vaccines contain antigens (killed/attenuated pathogens/toxoids) that stimulate the body's own immune response → production of antibodies and memory B and T cells → long-lasting active immunity.",
    tags: ["health and disease", "immunity", "vaccine", "active immunity"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Health and Disease",
    concept: "AIDS",
    year: 2017,
    difficulty: "MEDIUM" as const,
    questionText:
      "HIV (Human Immunodeficiency Virus) primarily infects and destroys:",
    optionA: "B lymphocytes",
    optionB: "Red blood cells",
    optionC: "CD4⁺ T helper lymphocytes",
    optionD: "Neutrophils",
    correctOption: "C" as const,
    explanation:
      "HIV binds to CD4 receptors on T helper cells (CD4⁺ T cells), enters and replicates, destroying these cells. This cripples cell-mediated immunity → AIDS (acquired immunodeficiency syndrome).",
    tags: ["health and disease", "HIV", "AIDS", "CD4 T cells"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Health and Disease",
    concept: "Malaria",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "Malaria is caused by Plasmodium species and transmitted by:",
    optionA: "Male Anopheles mosquito",
    optionB: "Female Anopheles mosquito",
    optionC: "Female Aedes mosquito",
    optionD: "Tsetse fly",
    correctOption: "B" as const,
    explanation:
      "Female Anopheles mosquito is the vector for malaria, transmitting Plasmodium (P. falciparum, P. vivax, P. malariae, P. ovale) during blood feeding. Male mosquitoes feed on plant nectar.",
    tags: ["health and disease", "malaria", "Plasmodium", "Anopheles"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Health and Disease",
    concept: "Allergy and hypersensitivity",
    year: 2015,
    difficulty: "MEDIUM" as const,
    questionText:
      "Allergic reactions are mediated by IgE antibodies and which type of cell?",
    optionA: "Cytotoxic T cells",
    optionB: "Mast cells (releasing histamine)",
    optionC: "B lymphocytes",
    optionD: "Natural killer cells",
    correctOption: "B" as const,
    explanation:
      "In allergies (Type I hypersensitivity), IgE antibodies bind to mast cells and basophils. Re-exposure to allergen → cross-linking of IgE → degranulation → histamine release → allergy symptoms.",
    tags: ["health and disease", "allergy", "IgE", "mast cells", "histamine"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Health and Disease",
    concept: "Cancer",
    year: 2024,
    difficulty: "HARD" as const,
    questionText:
      "Proto-oncogenes are normal cellular genes. They become oncogenes (cancer-causing) when:",
    optionA: "They are expressed normally",
    optionB: "They undergo mutation or are overexpressed",
    optionC: "They are suppressed",
    optionD: "They code for tumour suppressor proteins",
    correctOption: "B" as const,
    explanation:
      "Proto-oncogenes (like RAS, MYC) regulate normal cell growth. Mutations, chromosomal translocation, or amplification can convert them into oncogenes → uncontrolled cell division → cancer.",
    tags: ["health and disease", "cancer", "oncogenes", "proto-oncogene"],
  },

  // ─── GENETICS ─────────────────────────────────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Mendel's laws",
    year: 2018,
    difficulty: "EASY" as const,
    questionText:
      "In a monohybrid cross between Tt × Tt plants, the phenotypic ratio in F2 generation is:",
    optionA: "1:2:1",
    optionB: "3:1",
    optionC: "1:1",
    optionD: "9:3:3:1",
    correctOption: "B" as const,
    explanation:
      "Tt × Tt → TT : Tt : tt = 1:2:1 (genotypic ratio). Phenotypically, TT and Tt both show dominant trait → 3 dominant : 1 recessive = 3:1.",
    tags: ["genetics", "Mendel", "monohybrid cross", "phenotypic ratio"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Dihybrid cross",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "In a dihybrid cross (AaBb × AaBb), the F2 phenotypic ratio is:",
    optionA: "3:1",
    optionB: "1:2:1",
    optionC: "9:3:3:1",
    optionD: "1:1:1:1",
    correctOption: "C" as const,
    explanation:
      "Dihybrid F2 ratio is 9:3:3:1 (both dominant : dominant A only : dominant B only : both recessive), demonstrating Mendel's law of independent assortment.",
    tags: ["genetics", "dihybrid cross", "independent assortment", "9:3:3:1"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Sex-linked inheritance",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "Haemophilia A is an X-linked recessive disorder. A carrier female (X^H X^h) married to a normal male (X^H Y). What fraction of their sons will have haemophilia?",
    optionA: "All sons",
    optionB: "1/2 of sons",
    optionC: "No sons",
    optionD: "1/4 of all children",
    correctOption: "B" as const,
    explanation:
      "Cross: X^H X^h × X^H Y → X^H X^H, X^H X^h, X^H Y, X^h Y. Sons are X^H Y (normal) and X^h Y (haemophilic) in 1:1 ratio → 1/2 of sons will be affected.",
    tags: ["genetics", "haemophilia", "X-linked", "sex-linked inheritance"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Codominance",
    year: 2016,
    difficulty: "MEDIUM" as const,
    questionText:
      "In the ABO blood group system, persons with blood group AB show codominance because:",
    optionA: "A is dominant over B",
    optionB: "B is dominant over A",
    optionC: "Both I^A and I^B alleles are expressed simultaneously",
    optionD: "Neither I^A nor I^B is expressed",
    correctOption: "C" as const,
    explanation:
      "Codominance: both alleles are equally expressed. In genotype I^A I^B, both A and B antigens are produced on RBCs → Blood group AB. Neither allele is dominant over the other.",
    tags: ["genetics", "codominance", "ABO blood group", "multiple alleles"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Chromosomal disorders",
    year: 2021,
    difficulty: "HARD" as const,
    questionText:
      "Down syndrome (Trisomy 21) results from non-disjunction during meiosis. The karyotype shows:",
    optionA: "45 chromosomes (monosomy 21)",
    optionB: "47 chromosomes (trisomy 21)",
    optionC: "46 chromosomes with deletion",
    optionD: "48 chromosomes (tetrasomy)",
    correctOption: "B" as const,
    explanation:
      "Down syndrome karyotype: 47 chromosomes with three copies of chromosome 21 (2n+1 = 47). Features: intellectual disability, epicanthal folds, single palmar crease, heart defects.",
    tags: ["genetics", "Down syndrome", "trisomy 21", "non-disjunction"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Mutation",
    year: 2019,
    difficulty: "MEDIUM" as const,
    questionText:
      "Sickle cell anaemia is caused by a point mutation in the beta-globin gene. The change is:",
    optionA: "Insertion of an extra nucleotide",
    optionB: "Deletion of a codon",
    optionC: "Substitution of glutamic acid by valine (GAG → GTG)",
    optionD: "Frameshift mutation",
    correctOption: "C" as const,
    explanation:
      "Sickle cell anaemia is caused by a missense point mutation: GAG (Glu) → GUG/GTG (Val) at position 6 of β-globin. This causes HbS to polymerize under low O₂ conditions, distorting RBCs into sickle shape.",
    tags: ["genetics", "sickle cell anaemia", "point mutation", "missense mutation"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Hardy-Weinberg equilibrium",
    year: 2017,
    difficulty: "HARD" as const,
    questionText:
      "Hardy-Weinberg equilibrium is disrupted by all of the following EXCEPT:",
    optionA: "Natural selection",
    optionB: "Mutation",
    optionC: "Random mating",
    optionD: "Genetic drift",
    correctOption: "C" as const,
    explanation:
      "Hardy-Weinberg equilibrium requires: large population, random mating, no mutation, no migration, no selection. Random mating is a CONDITION for H-W equilibrium, not a disrupting factor.",
    tags: ["genetics", "Hardy-Weinberg", "evolution", "gene pool"],
  },

  // ─── ADDITIONAL MIXED QUESTIONS ───────────────────────────────────────────
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Classification – Reptilia",
    year: 2014,
    difficulty: "EASY" as const,
    questionText:
      "Which of the following is a cold-blooded (poikilothermic) animal?",
    optionA: "Bat",
    optionB: "Whale",
    optionC: "Crocodile",
    optionD: "Penguin",
    correctOption: "C" as const,
    explanation:
      "Crocodile is a reptile – a poikilotherm (ectotherm). Its body temperature varies with the environment. Bats, whales, and penguins are mammals (warm-blooded/homeothermic).",
    tags: ["animal kingdom", "Reptilia", "cold-blooded", "poikilotherm"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Digestion)",
    concept: "Liver functions",
    year: 2023,
    difficulty: "MEDIUM" as const,
    questionText:
      "The liver does NOT perform which of the following functions?",
    optionA: "Bile production",
    optionB: "Detoxification",
    optionC: "Insulin secretion",
    optionD: "Glycogen storage",
    correctOption: "C" as const,
    explanation:
      "Insulin is secreted by the beta cells of the pancreas (islets of Langerhans), not the liver. The liver produces bile, detoxifies drugs/alcohol, stores glycogen, and synthesizes plasma proteins.",
    tags: ["digestion", "liver", "functions", "insulin"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Circulation)",
    concept: "ECG",
    year: 2020,
    difficulty: "MEDIUM" as const,
    questionText:
      "In an ECG (electrocardiogram), the QRS complex represents:",
    optionA: "Atrial depolarization",
    optionB: "Ventricular depolarization",
    optionC: "Ventricular repolarization",
    optionD: "Atrial repolarization",
    correctOption: "B" as const,
    explanation:
      "P wave = atrial depolarization. QRS complex = ventricular depolarization (atrial repolarization is hidden). T wave = ventricular repolarization.",
    tags: ["circulation", "ECG", "QRS complex", "ventricular depolarization"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Excretion)",
    concept: "Juxtaglomerular apparatus",
    year: 2018,
    difficulty: "HARD" as const,
    questionText:
      "Renin, secreted by juxtaglomerular cells, ultimately leads to production of angiotensin II, which causes:",
    optionA: "Vasodilation and decreased blood pressure",
    optionB: "Vasoconstriction and increased aldosterone secretion",
    optionC: "Increased ADH inhibition",
    optionD: "Decreased Na⁺ reabsorption",
    correctOption: "B" as const,
    explanation:
      "RAAS: Renin (kidney) → Angiotensin I → Angiotensin II (ACE). Angiotensin II causes vasoconstriction (↑ BP) and stimulates aldosterone (adrenal cortex) → ↑ Na⁺/water reabsorption.",
    tags: ["excretion", "RAAS", "renin", "angiotensin", "aldosterone"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Reproduction",
    concept: "Contraception",
    year: 2022,
    difficulty: "MEDIUM" as const,
    questionText:
      "The copper-T (IUD) prevents pregnancy primarily by:",
    optionA: "Preventing ovulation",
    optionB: "Creating a hostile uterine environment and preventing fertilization/implantation",
    optionC: "Killing sperms in the vagina",
    optionD: "Blocking the fallopian tubes",
    correctOption: "B" as const,
    explanation:
      "Copper IUDs release Cu²⁺ ions that are toxic to sperm, impair sperm motility, and create an unfavorable uterine environment that prevents fertilization and implantation.",
    tags: ["reproduction", "contraception", "IUD", "copper-T"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Health and Disease",
    concept: "Drug abuse – narcotics",
    year: 2016,
    difficulty: "EASY" as const,
    questionText:
      "Heroin (diacetylmorphine) is derived from which plant?",
    optionA: "Cannabis sativa",
    optionB: "Erythroxylon coca",
    optionC: "Papaver somniferum (opium poppy)",
    optionD: "Atropa belladonna",
    correctOption: "C" as const,
    explanation:
      "Heroin is semi-synthetically derived from morphine, which is obtained from the opium poppy (Papaver somniferum). Cannabis gives marijuana/hashish; E. coca gives cocaine.",
    tags: ["health and disease", "drug abuse", "heroin", "opium poppy"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Genetics",
    concept: "Incomplete dominance",
    year: 2015,
    difficulty: "MEDIUM" as const,
    questionText:
      "In snapdragon (Antirrhinum), red (RR) × white (rr) gives pink (Rr) flowers. This is an example of:",
    optionA: "Codominance",
    optionB: "Incomplete dominance",
    optionC: "Epistasis",
    optionD: "Pleiotropy",
    correctOption: "B" as const,
    explanation:
      "Incomplete dominance: the heterozygote (Rr) shows an intermediate phenotype (pink) rather than one parental phenotype dominating. The F2 ratio is 1 Red : 2 Pink : 1 White (both genotypic and phenotypic).",
    tags: ["genetics", "incomplete dominance", "snapdragon", "intermediate phenotype"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Neural Control)",
    concept: "Eye – photoreception",
    year: 2021,
    difficulty: "MEDIUM" as const,
    questionText:
      "The photoreceptor cells responsible for colour vision in the human eye are:",
    optionA: "Rod cells (containing rhodopsin)",
    optionB: "Cone cells (containing iodopsin/photopsins)",
    optionC: "Bipolar cells",
    optionD: "Ganglion cells",
    correctOption: "B" as const,
    explanation:
      "Cone cells (S, M, L cones) contain different opsins sensitive to short, medium, and long wavelengths (blue, green, red). Rods contain rhodopsin and are responsible for dim/night vision.",
    tags: ["neural control", "eye", "cone cells", "colour vision", "photoreception"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Human Physiology (Endocrine)",
    concept: "Parathyroid hormone",
    year: 2019,
    difficulty: "HARD" as const,
    questionText:
      "Parathyroid hormone (PTH) raises blood calcium levels by:",
    optionA: "Increasing Ca²⁺ deposition in bones",
    optionB: "Increasing Ca²⁺ reabsorption in kidneys and Ca²⁺ release from bones",
    optionC: "Decreasing intestinal Ca²⁺ absorption",
    optionD: "Stimulating calcitonin secretion",
    correctOption: "B" as const,
    explanation:
      "PTH (from parathyroid glands) raises blood Ca²⁺ by: (1) stimulating osteoclasts to resorb bone Ca²⁺, (2) increasing Ca²⁺ reabsorption in the kidney, (3) activating Vitamin D for intestinal Ca²⁺ absorption.",
    tags: ["endocrine", "PTH", "calcium", "parathyroid"],
  },
  {
    subject: "ZOOLOGY" as const,
    chapter: "Animal Kingdom",
    concept: "Classification – Mammalia",
    year: 2024,
    difficulty: "MEDIUM" as const,
    questionText:
      "Monotremes (e.g., platypus, echidna) are unique among mammals because they:",
    optionA: "Have a placenta",
    optionB: "Are cold-blooded",
    optionC: "Lay eggs (oviparous) but nurse young with milk",
    optionD: "Lack hair",
    correctOption: "C" as const,
    explanation:
      "Monotremes are the most primitive mammals. They lay leathery eggs (oviparous) but suckle young with milk secreted through skin pores (no nipples). They also lack teeth as adults.",
    tags: ["animal kingdom", "Mammalia", "monotremes", "platypus", "oviparous"],
  },
];
